PEOPLE = (
    'Albert Einstein',
    'Freddie Mercury',
    'Obama',
    'Mark Twain',
    'Queen Elizabeth',
    'Sun Tzu',
    'Nikola Tesla',
    'Adolf Hitler',
    '6ix9ine',
    'Taylor Swift',
    'Ur Mum',
    'Dumbledore',
    'Gandalf',
    'Hermione',
    'Godzilla',
    'Genghis Khan',
    'Omni-Man',
    'Chuck Norris',
    'Oompa Loompas',
    'Squidward',
    'Elon Musk',
    'Reanu Keeves',
    'Keanu Reeves',
    'Gimli\'s beard',
    'Cardi O',
    'Wendy\'s',
    'Quentin Tarantino',
    'Rick Astley',
    'Kim Jong Un',
    'Doom Slayer',
    'Sauron',
    'The Dragonborn',
    'Geralt of Rivia',
    'Cheems',
    'Jake Paul',
    'Jesus',
    'Big Chungus',
    'Ur Doppelganger',
    'Kami Sama',
    'Jonathan Joestar',
    'Patrick',
    'T-Series',
    'Sasuke',
    'Shrek',
    'Kenshin',
    'Cheems',
)