PROFANITIES = (
    '**BANGSAT**',
    '**GOBLOK**',
    '**ANJING**',
    '**MEMEK**',
    '**PUKI**',
    '**CIBAI**',
    '**KONTOL**',
    '**JANCOK**',
    '**BABI**',
    '**ASU**',
    '**BAJINGAN**',
    '**TELASO**',
    '**TAI**',
    '**TAEK**',
    '**TOLOL**',
    '**JEMBUT**',
    '**PALKON**',
    '**PANTEK**',
    '**KAMPANG**',
    '**KIMAK**',
    '**HENCEUT BEUREUM**',
    '**FUCK**',
    '**SHIT**',
    '**ASSHOLE**',
    '**DICKHEAD**',
    '**CUNT**',
    '**FUCKING CUNT**',
    '**HOE**',
    '**BITCH**',
    '**FAGGOT**',
    '**NIGGA**',
    '**NIGGER**',
    '**SLUT**',
    '**PRICK**',
    '**WANKER**',
    '**DUMBASS**',
    '**MOTHERFUCKER**',
    '**GODDAMN**',
    '**BULLSHIT**',
    '**ARSEHOLE**',
    '**JESUS FUCKING CHRIST**',
    '**SON OF A BITCH**',
    '**PRICK**',
    '**DONG**',
    '**PUSSY ASS NIGGA**',
    '**PUSSY**',
    '**BASTARD**',
)